server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rengawDB
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: zulfiqar9726@gmail.com
    password: tyqhivggoncfebug
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
